# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: d075e659dcfea6d8c0657e4544cfc08449426bbf2d6a37d6bb69b9ab716e56811c839f43e93a548a1be7277ad25ee26bf46e70d5f520f50a6acb3e039068558b

test:
  secret_key_base: cbb5f793b20d626444298d1b950cc23f83796cc374b7180bd34dedb8e67d076d3f877e9bc5419d4fedf4d03b8cdec1a2e13bf851194463b62b71f490996951e1

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
